wEbProje/WebApp/Controllers/AdminController.cs
using DataAccess.Concrete.EntityFramework;
using Entities.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
	[Authorize]
	public class AdminController : Controller
    {
        readonly UserManager<AppUser> userManager;

        public AdminController(UserManager<AppUser> userManager)
        {
            this.userManager = userManager;
        }

        public IActionResult Index()
        {
            var users = userManager.Users;
            return View(users);
        }

        public async Task<IActionResult> UserSil(string UserName)
        {
            AppUser user = new AppUser();
            user = await  userManager.FindByNameAsync(UserName);
            await userManager.DeleteAsync(user);

            return RedirectToAction("Index");
        
        }
    }
}

wEbProje/WebApp/Controllers/KitapController.cs
using Business.Concrete;
using DataAccess.Abstract;
using DataAccess.Concrete.EntityFramework;
using Entities.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models;

namespace WebApp.Controllers
{
	[Authorize]
	public class KitapController : Controller
    {
        KitapManager km = new KitapManager(new EfKitapDal());

        [Authorize]
        public IActionResult Index()
        {
            var kitaplar = km.GetAll();
            return View(kitaplar); 
        }
        [Authorize]
        public IActionResult KitapDetaylari(int id)
        {
            if(id == null)
            {
                return NotFound();
            }

            var kitap = km.YazarVeKitap(id);

            return View(kitap);
        }

        public IActionResult KitapSil (int KitapID)
        {
            KitapContext k = new KitapContext();
            Kitap silinecekKitap = new Kitap();
            silinecekKitap = km.GetById(KitapID);

            var silinecekYorum = k.Yorums.Where(y => y.KitapID == silinecekKitap.KitapID).ToList();
            k.Yorums.RemoveRange(silinecekYorum);
            k.SaveChanges();
            km.Delete(silinecekKitap);
            return RedirectToAction("Index", "Admin");
        }

        public IActionResult KitapEkle()
        {
            return View();
        }
        [HttpPost]
        public IActionResult KitapEkle(KitapResmiEkle kResim)
        {
            Kitap kitap = new Kitap();
            if (kResim.KitapResmi != null) {
                var extension = Path.GetExtension(kResim.KitapResmi.FileName);
                var newImageName = Guid.NewGuid() + extension;
                var location = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Resimler/KitapResimleri/", newImageName);
                var stream = new FileStream(location, FileMode.Create);
                kResim.KitapResmi.CopyTo(stream);
                kitap.KitapResmi = "Resimler/KitapResimleri/"+newImageName;
            }
            else
            {
                return View("KitapEkle");
            }
            kitap.KitapTanimi = kResim.KitapTanimi;
            kitap.KitapAdi    = kResim.KitapAdi;
            kitap.YayinEvi    = kResim.YayinEvi;
            kitap.YazarID     = kResim.YazarID;
            km.Add(kitap);
            return RedirectToAction("Index","Admin");
        }

    }
}

wEbProje/WebApp/Views/Admin/Index.cshtml
@model IQueryable<Entities.Identity.AppUser>
@using Entities.Identity;
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager

    <head>
       
  
  
    </head>
<div class="container">
    <h2>Admin Paneli</h2>
    <ul class="nav nav-tabs ">
        <li class=" btn btn-light mr-2"><a class="btn" data-toggle="tab" href="#user">Kullanıcılar</a></li>
        <li class=" btn btn-light mr-2"><a class="btn" data-toggle="tab" href="#kitap">Kitaplar</a></li>
        <li class=" btn btn-light"><a class="btn" data-toggle="tab" href="#yorum">Yorumlar</a></li>
        
    </ul>

    <div class="tab-content">
        <div id="user" class="tab-pane fade ">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Kullanıcılar</h6>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                                <tr>
                                    <th>Kullanıcı Adı</th>
                                    <th>Adı</th>
                                    <th>Soyadı</th>
                                    <th>Email</th>
                                    <th>Kullanıcıyı Sil</th>

                                </tr>
                            </thead>

                            @foreach (var item in Model)
                            {
                                <tbody>
                                    <tr>
                                        <td>@item.UserName</td>
                                        <td>@item.Name</td>
                                        <td>@item.Surname</td>
                                        <td>@item.Email</td>
                                        <td> <a class="btn btn-danger btn-lg active btn-sm " asp-controller="Admin" asp-action="UserSil" asp-route-UserName="@item.UserName">Sil</a></td>


                                    </tr>

                                </tbody>
                            }
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div id="kitap" class="tab-pane fade">

            <div class="card shadow mb-4">
                @await Component.InvokeAsync("AdminKitaplar")

            </div>
            <a asp-controller="Kitap" asp-action="KitapEkle" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Kitap Ekle</a>
        </div>
        <div id="yorum" class="tab-pane fade">

            <div class="card shadow mb-4">
                @await Component.InvokeAsync("AdminYorum")

            </div>
        </div>
    </div>
</div>