wEbProje/WebApp/Controllers/LoginController.cs
using Business.Concrete;
using DataAccess.Concrete.EntityFramework;
using Entities.Concrete;
using Entities.Identity;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Security.Claims;
using WebApp.Models;
using WebApp.Models.View_Model;

namespace WebApp.Controllers
{
	public class LoginController : Controller
	{


        readonly SignInManager<AppUser> signInManager;
        readonly UserManager<AppUser> userManager;

        public LoginController(SignInManager<AppUser> signInManager, UserManager<AppUser> userManager)
        {
            this.signInManager = signInManager;
            this.userManager = userManager;
        }

        public IActionResult Index()
		{
			return View();
		}

        [HttpPost]
        public IActionResult Cookie(string culture)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.Now.AddDays(10) }
            );

            return RedirectToAction("Index");
        }


        [HttpPost]
        public async Task<IActionResult> Login(UserSignInViewModel user)
        {
            if (ModelState.IsValid)
            {
                var neden = userManager.FindByEmailAsync(user.Username);

                if(neden.Result != null)
                {
                    var result = await signInManager.PasswordSignInAsync(neden.Result, user.Password, true, false);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index", "Kitap");
                    }
                    else
                    {
                        TempData["hata"] = "Böyle bir kullanıcı yok! Lütfen tekrar giriş yapmayı deneyiniz.";
                        return View("Index");
                    }
                }
                else
                {
                    TempData["hata"] = "Böyle bir kullanıcı yok! Lütfen tekrar giriş yapmayı deneyiniz.";
                    return View("Index");
                }
            }
            return View("Index");
           
        }

        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return View("Index");
           
        }


    }
}
//else
//{
//    
//    return View("Index");
//}

wEbProje/WebApp/Controllers/RegisterController.cs
using Entities.Identity;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models.View_Model;

namespace WebApp.Controllers
{
    public class RegisterController : Controller
    {
        readonly UserManager<AppUser> userManager;

        public RegisterController(UserManager<AppUser> userManager)
        {
            this.userManager = userManager;
        }

        public IActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Cookie(string culture)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.Now.AddDays(10) }
            );

            return RedirectToAction("Index");
        }


        [HttpPost]
        public async Task<IActionResult> Register(UserSignUpViewModel user)
        {
            if (ModelState.IsValid)
            {
                AppUser appUser = new AppUser
                {
                    
                    Email = user.Email,
                    UserName = user.UserName,
                    Name = user.Name,
                    Surname = user.Surname
                };
                

                var result = await userManager.CreateAsync(appUser, user.Password);
                

                if (result.Succeeded)
                {
                    await userManager.AddToRoleAsync(appUser, "Kullanici");
                    return RedirectToAction("Index", "Login");
                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError("", item.Description);
                    }
                }

            }


            else
            {
                TempData["msj"] = "lütfen gerekli alanları doldurunuz";
            }


            return View("Index");
        }
    }
}

wEbProje/WebApp/Views/Login/Index.cshtml
@using Microsoft.AspNetCore.Localization;
@using Microsoft.Extensions.Options;
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

    @{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}




@{
    string culture = "", uiculture = "";
    if (Context.Request.QueryString.HasValue)
    {
        string url = Context.Request.QueryString.Value;
        culture = Context.Request.Query["culture"];
        uiculture = Context.Request.Query["ui-culture"];
    }
}

@model WebApp.Models.View_Model.UserSignInViewModel
@{
    Layout = null;
}
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Register</title>

    <!-- Custom fonts for this template-->
    <link href="~/startbootstrap-sb-admin-2-gh-pages/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/startbootstrap-sb-admin-2-gh-pages/css/sb-admin-2.min.css" rel="stylesheet">

</head>


<div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <div class="p-2">
                <form asp-action="Cookie" method="post">
                    <label>@localizer["dil"]</label>
                    <select class="custom-select-sm" name="culture" onchange="this.form.submit()" asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems">
                    </select>
                </form>
            </div>
            <!-- Nested Row within Card Body -->
            <div class="row" style="justify-content:center">

                <div class="col-lg-7">

                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">@localizer["Title"]</h1>
                            @if (TempData["hata"] != null)
{
                            <div class="text-center row">
                                <h4 style="color:red">@TempData["hata"]</h4>
                                <div class="col-md-4"></div>
                                <hr class="col-md-4" />
                            </div>
    
}
                        </div>
                        <form asp-action="Login" method="post">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            
                            <div class="form-group row">
                                
                                <div class="col-sm-6">
                                    <label hidden asp-for="Username"></label>
                                    <input asp-for="Username" type="text" class="form-control form-control-user" id="exampleInputEmail"
                                           placeholder="@localizer["email_place"]">
                                    <span asp-validation-for="Username" class="text-danger"></span>
                                </div>
                                <div class="col-sm-6 mb-3 mb-sm-0">
                                    <label hidden asp-for="Password"></label>
                                    <input asp-for="Password" type="password" class="form-control form-control-user"
                                           placeholder="@localizer["pass_place"]">
                                    <span asp-validation-for="Password" class="text-danger"></span>
                                </div>
                            </div>
                            
                            <input class="btn btn-primary btn-user btn-block" type="submit" value="@localizer["Login"]" />
                            <hr>

                        </form>
                        

                        <div class="text-center">
                            <a class="small" asp-controller="Register" asp-action="Index">@localizer["reg"]</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

<!-- Bootstrap core JavaScript-->
<script src="~/startbootstrap-sb-admin-2-gh-pages/vendor/jquery/jquery.min.js"></script>
<script src="~/startbootstrap-sb-admin-2-gh-pages/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Core plugin JavaScript-->
<script src="~/startbootstrap-sb-admin-2-gh-pages/vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom scripts for all pages-->
<script src="~/startbootstrap-sb-admin-2-gh-pages/js/sb-admin-2.min.js"></script>
@*<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
        <form asp-action="Login" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="mb-3">
                <label asp-for="Username" class="control-label">Email adresi</label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            
            <div class="mb-3">
                <label asp-for="Password" class="control-label">Şifre</label>
                <input asp-for="Password" type="password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Giriş Yap!" class="btn btn-primary" />
                <input type="submit" value="Kayıt Ol!" class="btn btn-primary" asp-controller="Register" asp-action="Index" />
            </div>
        </form>
    </div>
</div>*@

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}