wEbProje/WebApp/Controllers/YorumController.cs
using Business.Concrete;
using DataAccess.Concrete.EntityFramework;
using Entities.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Controllers
{
	[Authorize]
	public class YorumController : Controller
    {
        YorumManager km = new YorumManager(new EfYorumDal());
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Yorumla(Yorum yorum)
        {
            yorum.YorumBaslık = "on";
            yorum.YorumTarih=DateTime.Now;
            
            
                km.Add(yorum);
                
               
                return RedirectToAction("KitapDetaylari", "Kitap",new {id=yorum.KitapID});
            

        }

        
        public IActionResult YorumSil(int YorumID)
        {
            Yorum y = new Yorum();

            y= km.GetById(YorumID);
            int kitapID = y.KitapID;
            km.Delete(y);

            return RedirectToAction("KitapDetaylari", "Kitap", new { id = kitapID });
        }
    }
}

wEbProje/WebApp/Views/Shared/Components/Yorumlar/Default.cshtml
@using Entities.Identity;
@using Microsoft.AspNetCore.Identity;
@model List<Entities.Concrete.Yorum>
@inject SignInManager<AppUser> SignInManager
@inject UserManager<AppUser> UserManager


    @if (SignInManager.IsSignedIn(User))
    {
        
    


<div class="col-lg-8 ">


    <div >
            <h4 class="fw-bold" style="font-family:'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif"><b>Yorumlar | @Model.Count</b></h4>
        @foreach (var item in Model)
        {
            <hr />
            <div class="media">

            <div class="media-body">
                        <h5 class="mt-0"><b>@item.YorumAd</b></h5>
                        <p class="small">@item.YorumTarih  |
                        @if(User.Identity.Name == item.YorumAd || User.IsInRole("Admin"))
                        {   
                            
                              <a class="btn-sm btn btn-dark ml-3" asp-controller="Yorum" asp-action="YorumSil" asp-route-YorumID="@item.YorumID">Sil</a>
                            
                        }
                                </p>
                        <p class="text-gray-800">
                   @item.YorumIcerik
                </p>
            </div>
        </div>
        }
        
    </div>
    <hr />

        
    </div>
}